import { ref, shallowRef } from 'vue'

/**
 * Loads the JSON manifests that drive all "drop a file in and it appears"
 * content: vehicles, reviews and videos.
 *
 * The manifests live in `public/data/` and are regenerated by
 * `scripts/scan-assets.mjs`, so adding a photo or video to the matching
 * folder is all it takes to update the site.
 */

const cache = new Map()

async function loadJson(url) {
  if (cache.has(url)) return cache.get(url)
  const task = (async () => {
    try {
      const res = await fetch(url, { cache: 'no-cache' })
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`)
      return await res.json()
    } catch (err) {
      if (import.meta.env?.DEV) {
        console.warn(`[manifest] could not load ${url}`, err)
      }
      return null
    }
  })()
  cache.set(url, task)
  return task
}

/**
 * @param {string} file  manifest filename inside /data, e.g. 'reviews.json'
 * @param {Array|Object} fallback  used when the manifest is missing
 */
export function useManifest(file, fallback = []) {
  const data = shallowRef(fallback)
  const loading = ref(true)
  const ready = ref(false)

  const url = `${import.meta.env?.BASE_URL || '/'}data/${file}`.replace('//data', '/data')

  const promise =
    typeof window === 'undefined'
      ? Promise.resolve(null)
      : loadJson(url).then((json) => {
          if (json !== null && json !== undefined) {
            data.value = Array.isArray(fallback)
              ? Array.isArray(json)
                ? json
                : (json.items ?? fallback)
              : { ...fallback, ...json }
          }
          loading.value = false
          ready.value = true
          return data.value
        })

  return { data, loading, ready, promise, refresh: () => cache.delete(url) }
}

/** Same as useManifest but leaves the caller to await it (used in setup). */
export async function fetchManifest(file, fallback = []) {
  const json = await loadJson(`/data/${file}`)
  if (json === null || json === undefined) return fallback
  return json
}
